language: go
dist: xenial
sudo: required
services:
  - docker
env:
  global:
    - TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG#*/}
    - TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG%/*}
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - cd ${TRAVIS_BUILD_DIR}/dockerfiles
  - make build
  - make push
  - cd ${TRAVIS_BUILD_DIR}/${TRAVIS_REPO_NAME}-agent/dockerfiles
  - make build
  - make push
