// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metanet.proto

package caffe2

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ModelInfo struct {
	Project       string  `protobuf:"bytes,1,opt,name=project" json:"project"`
	ModelClass    string  `protobuf:"bytes,2,opt,name=modelClass" json:"modelClass"`
	Version       string  `protobuf:"bytes,3,opt,name=version" json:"version"`
	PredictorType *string `protobuf:"bytes,4,opt,name=predictorType,def=SINGLE_PREDICTOR" json:"predictorType,omitempty"`
	ModelId       string  `protobuf:"bytes,5,opt,name=modelId" json:"modelId"`
}

func (m *ModelInfo) Reset()         { *m = ModelInfo{} }
func (m *ModelInfo) String() string { return proto.CompactTextString(m) }
func (*ModelInfo) ProtoMessage()    {}
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_metanet_97b3d41dff9f250c, []int{0}
}
func (m *ModelInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ModelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ModelInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ModelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelInfo.Merge(dst, src)
}
func (m *ModelInfo) XXX_Size() int {
	return m.Size()
}
func (m *ModelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ModelInfo proto.InternalMessageInfo

const Default_ModelInfo_PredictorType string = "SINGLE_PREDICTOR"

func (m *ModelInfo) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ModelInfo) GetModelClass() string {
	if m != nil {
		return m.ModelClass
	}
	return ""
}

func (m *ModelInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ModelInfo) GetPredictorType() string {
	if m != nil && m.PredictorType != nil {
		return *m.PredictorType
	}
	return Default_ModelInfo_PredictorType
}

func (m *ModelInfo) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

type BlobsMap struct {
	Key   string   `protobuf:"bytes,1,req,name=key" json:"key"`
	Value []string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
}

func (m *BlobsMap) Reset()         { *m = BlobsMap{} }
func (m *BlobsMap) String() string { return proto.CompactTextString(m) }
func (*BlobsMap) ProtoMessage()    {}
func (*BlobsMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_metanet_97b3d41dff9f250c, []int{1}
}
func (m *BlobsMap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlobsMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlobsMap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *BlobsMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobsMap.Merge(dst, src)
}
func (m *BlobsMap) XXX_Size() int {
	return m.Size()
}
func (m *BlobsMap) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobsMap.DiscardUnknown(m)
}

var xxx_messageInfo_BlobsMap proto.InternalMessageInfo

func (m *BlobsMap) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *BlobsMap) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type NetsMap struct {
	Key   string  `protobuf:"bytes,1,req,name=key" json:"key"`
	Value *NetDef `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
}

func (m *NetsMap) Reset()         { *m = NetsMap{} }
func (m *NetsMap) String() string { return proto.CompactTextString(m) }
func (*NetsMap) ProtoMessage()    {}
func (*NetsMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_metanet_97b3d41dff9f250c, []int{2}
}
func (m *NetsMap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NetsMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NetsMap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *NetsMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetsMap.Merge(dst, src)
}
func (m *NetsMap) XXX_Size() int {
	return m.Size()
}
func (m *NetsMap) XXX_DiscardUnknown() {
	xxx_messageInfo_NetsMap.DiscardUnknown(m)
}

var xxx_messageInfo_NetsMap proto.InternalMessageInfo

func (m *NetsMap) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *NetsMap) GetValue() *NetDef {
	if m != nil {
		return m.Value
	}
	return nil
}

type PlansMap struct {
	Key   string   `protobuf:"bytes,1,req,name=key" json:"key"`
	Value *PlanDef `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
}

func (m *PlansMap) Reset()         { *m = PlansMap{} }
func (m *PlansMap) String() string { return proto.CompactTextString(m) }
func (*PlansMap) ProtoMessage()    {}
func (*PlansMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_metanet_97b3d41dff9f250c, []int{3}
}
func (m *PlansMap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PlansMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PlansMap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *PlansMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlansMap.Merge(dst, src)
}
func (m *PlansMap) XXX_Size() int {
	return m.Size()
}
func (m *PlansMap) XXX_DiscardUnknown() {
	xxx_messageInfo_PlansMap.DiscardUnknown(m)
}

var xxx_messageInfo_PlansMap proto.InternalMessageInfo

func (m *PlansMap) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PlansMap) GetValue() *PlanDef {
	if m != nil {
		return m.Value
	}
	return nil
}

type StringMap struct {
	Key   string `protobuf:"bytes,1,req,name=key" json:"key"`
	Value string `protobuf:"bytes,2,req,name=value" json:"value"`
}

func (m *StringMap) Reset()         { *m = StringMap{} }
func (m *StringMap) String() string { return proto.CompactTextString(m) }
func (*StringMap) ProtoMessage()    {}
func (*StringMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_metanet_97b3d41dff9f250c, []int{4}
}
func (m *StringMap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StringMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StringMap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *StringMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMap.Merge(dst, src)
}
func (m *StringMap) XXX_Size() int {
	return m.Size()
}
func (m *StringMap) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMap.DiscardUnknown(m)
}

var xxx_messageInfo_StringMap proto.InternalMessageInfo

func (m *StringMap) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StringMap) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MetaNetDef struct {
	Blobs []*BlobsMap `protobuf:"bytes,1,rep,name=blobs" json:"blobs,omitempty"`
	// Text-format serialized NetDefs.
	Nets []*NetsMap `protobuf:"bytes,2,rep,name=nets" json:"nets,omitempty"`
	// Info about where the model comes from. Possible use cases:
	// 1) sanity check or diagnose
	// 2) provide info for evaluation.
	ModelInfo               *ModelInfo   `protobuf:"bytes,3,opt,name=modelInfo" json:"modelInfo,omitempty"`
	Plans                   []*PlansMap  `protobuf:"bytes,4,rep,name=plans" json:"plans,omitempty"`
	ApplicationSpecificInfo []*StringMap `protobuf:"bytes,5,rep,name=applicationSpecificInfo" json:"applicationSpecificInfo,omitempty"`
}

func (m *MetaNetDef) Reset()         { *m = MetaNetDef{} }
func (m *MetaNetDef) String() string { return proto.CompactTextString(m) }
func (*MetaNetDef) ProtoMessage()    {}
func (*MetaNetDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_metanet_97b3d41dff9f250c, []int{5}
}
func (m *MetaNetDef) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetaNetDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetaNetDef.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MetaNetDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaNetDef.Merge(dst, src)
}
func (m *MetaNetDef) XXX_Size() int {
	return m.Size()
}
func (m *MetaNetDef) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaNetDef.DiscardUnknown(m)
}

var xxx_messageInfo_MetaNetDef proto.InternalMessageInfo

func (m *MetaNetDef) GetBlobs() []*BlobsMap {
	if m != nil {
		return m.Blobs
	}
	return nil
}

func (m *MetaNetDef) GetNets() []*NetsMap {
	if m != nil {
		return m.Nets
	}
	return nil
}

func (m *MetaNetDef) GetModelInfo() *ModelInfo {
	if m != nil {
		return m.ModelInfo
	}
	return nil
}

func (m *MetaNetDef) GetPlans() []*PlansMap {
	if m != nil {
		return m.Plans
	}
	return nil
}

func (m *MetaNetDef) GetApplicationSpecificInfo() []*StringMap {
	if m != nil {
		return m.ApplicationSpecificInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*ModelInfo)(nil), "caffe2.ModelInfo")
	proto.RegisterType((*BlobsMap)(nil), "caffe2.BlobsMap")
	proto.RegisterType((*NetsMap)(nil), "caffe2.NetsMap")
	proto.RegisterType((*PlansMap)(nil), "caffe2.PlansMap")
	proto.RegisterType((*StringMap)(nil), "caffe2.StringMap")
	proto.RegisterType((*MetaNetDef)(nil), "caffe2.MetaNetDef")
}
func (m *ModelInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ModelInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMetanet(dAtA, i, uint64(len(m.Project)))
	i += copy(dAtA[i:], m.Project)
	dAtA[i] = 0x12
	i++
	i = encodeVarintMetanet(dAtA, i, uint64(len(m.ModelClass)))
	i += copy(dAtA[i:], m.ModelClass)
	dAtA[i] = 0x1a
	i++
	i = encodeVarintMetanet(dAtA, i, uint64(len(m.Version)))
	i += copy(dAtA[i:], m.Version)
	if m.PredictorType != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMetanet(dAtA, i, uint64(len(*m.PredictorType)))
		i += copy(dAtA[i:], *m.PredictorType)
	}
	dAtA[i] = 0x2a
	i++
	i = encodeVarintMetanet(dAtA, i, uint64(len(m.ModelId)))
	i += copy(dAtA[i:], m.ModelId)
	return i, nil
}

func (m *BlobsMap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlobsMap) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMetanet(dAtA, i, uint64(len(m.Key)))
	i += copy(dAtA[i:], m.Key)
	if len(m.Value) > 0 {
		for _, s := range m.Value {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *NetsMap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetsMap) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMetanet(dAtA, i, uint64(len(m.Key)))
	i += copy(dAtA[i:], m.Key)
	if m.Value == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("value")
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMetanet(dAtA, i, uint64(m.Value.Size()))
		n1, err := m.Value.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *PlansMap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlansMap) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMetanet(dAtA, i, uint64(len(m.Key)))
	i += copy(dAtA[i:], m.Key)
	if m.Value == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("value")
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMetanet(dAtA, i, uint64(m.Value.Size()))
		n2, err := m.Value.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}

func (m *StringMap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StringMap) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintMetanet(dAtA, i, uint64(len(m.Key)))
	i += copy(dAtA[i:], m.Key)
	dAtA[i] = 0x12
	i++
	i = encodeVarintMetanet(dAtA, i, uint64(len(m.Value)))
	i += copy(dAtA[i:], m.Value)
	return i, nil
}

func (m *MetaNetDef) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetaNetDef) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Blobs) > 0 {
		for _, msg := range m.Blobs {
			dAtA[i] = 0xa
			i++
			i = encodeVarintMetanet(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Nets) > 0 {
		for _, msg := range m.Nets {
			dAtA[i] = 0x12
			i++
			i = encodeVarintMetanet(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.ModelInfo != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMetanet(dAtA, i, uint64(m.ModelInfo.Size()))
		n3, err := m.ModelInfo.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if len(m.Plans) > 0 {
		for _, msg := range m.Plans {
			dAtA[i] = 0x22
			i++
			i = encodeVarintMetanet(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.ApplicationSpecificInfo) > 0 {
		for _, msg := range m.ApplicationSpecificInfo {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintMetanet(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func encodeVarintMetanet(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ModelInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Project)
	n += 1 + l + sovMetanet(uint64(l))
	l = len(m.ModelClass)
	n += 1 + l + sovMetanet(uint64(l))
	l = len(m.Version)
	n += 1 + l + sovMetanet(uint64(l))
	if m.PredictorType != nil {
		l = len(*m.PredictorType)
		n += 1 + l + sovMetanet(uint64(l))
	}
	l = len(m.ModelId)
	n += 1 + l + sovMetanet(uint64(l))
	return n
}

func (m *BlobsMap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	n += 1 + l + sovMetanet(uint64(l))
	if len(m.Value) > 0 {
		for _, s := range m.Value {
			l = len(s)
			n += 1 + l + sovMetanet(uint64(l))
		}
	}
	return n
}

func (m *NetsMap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	n += 1 + l + sovMetanet(uint64(l))
	if m.Value != nil {
		l = m.Value.Size()
		n += 1 + l + sovMetanet(uint64(l))
	}
	return n
}

func (m *PlansMap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	n += 1 + l + sovMetanet(uint64(l))
	if m.Value != nil {
		l = m.Value.Size()
		n += 1 + l + sovMetanet(uint64(l))
	}
	return n
}

func (m *StringMap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	n += 1 + l + sovMetanet(uint64(l))
	l = len(m.Value)
	n += 1 + l + sovMetanet(uint64(l))
	return n
}

func (m *MetaNetDef) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Blobs) > 0 {
		for _, e := range m.Blobs {
			l = e.Size()
			n += 1 + l + sovMetanet(uint64(l))
		}
	}
	if len(m.Nets) > 0 {
		for _, e := range m.Nets {
			l = e.Size()
			n += 1 + l + sovMetanet(uint64(l))
		}
	}
	if m.ModelInfo != nil {
		l = m.ModelInfo.Size()
		n += 1 + l + sovMetanet(uint64(l))
	}
	if len(m.Plans) > 0 {
		for _, e := range m.Plans {
			l = e.Size()
			n += 1 + l + sovMetanet(uint64(l))
		}
	}
	if len(m.ApplicationSpecificInfo) > 0 {
		for _, e := range m.ApplicationSpecificInfo {
			l = e.Size()
			n += 1 + l + sovMetanet(uint64(l))
		}
	}
	return n
}

func sovMetanet(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMetanet(x uint64) (n int) {
	return sovMetanet(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ModelInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetanet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ModelInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ModelInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Project", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Project = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelClass", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelClass = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PredictorType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.PredictorType = &s
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetanet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetanet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlobsMap) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetanet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlobsMap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlobsMap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetanet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetanet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("key")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NetsMap) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetanet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetsMap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetsMap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Value == nil {
				m.Value = &NetDef{}
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipMetanet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetanet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("key")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("value")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlansMap) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetanet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlansMap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlansMap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Value == nil {
				m.Value = &PlanDef{}
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipMetanet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetanet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("key")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("value")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StringMap) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetanet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StringMap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StringMap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipMetanet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetanet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("key")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("value")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetaNetDef) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetanet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetaNetDef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetaNetDef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Blobs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Blobs = append(m.Blobs, &BlobsMap{})
			if err := m.Blobs[len(m.Blobs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nets = append(m.Nets, &NetsMap{})
			if err := m.Nets[len(m.Nets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ModelInfo == nil {
				m.ModelInfo = &ModelInfo{}
			}
			if err := m.ModelInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plans", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Plans = append(m.Plans, &PlansMap{})
			if err := m.Plans[len(m.Plans)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationSpecificInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetanet
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApplicationSpecificInfo = append(m.ApplicationSpecificInfo, &StringMap{})
			if err := m.ApplicationSpecificInfo[len(m.ApplicationSpecificInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetanet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetanet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMetanet(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMetanet
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetanet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMetanet
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMetanet
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMetanet(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMetanet = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetanet   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("metanet.proto", fileDescriptor_metanet_97b3d41dff9f250c) }

var fileDescriptor_metanet_97b3d41dff9f250c = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0xeb, 0xb6, 0x61, 0xcb, 0x2b, 0x83, 0x61, 0x21, 0xb0, 0x76, 0x08, 0x51, 0x19, 0x28,
	0xa7, 0x21, 0xe5, 0x80, 0x10, 0x17, 0xa4, 0x6e, 0xd3, 0x14, 0x41, 0xcb, 0xe4, 0xee, 0x8e, 0xbc,
	0xf4, 0x05, 0x05, 0xd2, 0xd8, 0x4a, 0xcc, 0xa4, 0xfd, 0x17, 0xfc, 0x59, 0xe3, 0xb6, 0x23, 0x27,
	0x84, 0xda, 0x3f, 0x04, 0xe4, 0x24, 0xce, 0xd2, 0xc3, 0x7a, 0x8a, 0xf2, 0xbd, 0xef, 0xfd, 0x3e,
	0xeb, 0xb3, 0x61, 0x6f, 0x89, 0x5a, 0xe4, 0xa8, 0x8f, 0x54, 0x21, 0xb5, 0xa4, 0x0f, 0x62, 0x91,
	0x24, 0x18, 0x1e, 0x3c, 0xac, 0xbf, 0xb5, 0x3a, 0xfe, 0x45, 0xc0, 0x9d, 0xca, 0x05, 0x66, 0x51,
	0x9e, 0x48, 0xea, 0xc1, 0x8e, 0x2a, 0xe4, 0x37, 0x8c, 0x35, 0x23, 0x3e, 0x09, 0xdc, 0xc9, 0xf0,
	0xe6, 0xcf, 0x8b, 0x1e, 0xb7, 0x22, 0x3d, 0x04, 0x58, 0x1a, 0xf3, 0x71, 0x26, 0xca, 0x92, 0xf5,
	0x3b, 0x96, 0x8e, 0x6e, 0x28, 0x57, 0x58, 0x94, 0xa9, 0xcc, 0xd9, 0xa0, 0x4b, 0x69, 0x44, 0xfa,
	0x16, 0xf6, 0x54, 0x81, 0x8b, 0x34, 0xd6, 0xb2, 0xb8, 0xb8, 0x56, 0xc8, 0x86, 0xc6, 0xf5, 0x7e,
	0x7f, 0x1e, 0xcd, 0xce, 0x3e, 0x9d, 0x7e, 0x39, 0xe7, 0xa7, 0x27, 0xd1, 0xf1, 0xc5, 0x67, 0xce,
	0x37, 0x6d, 0x86, 0x5b, 0xa5, 0x44, 0x0b, 0xe6, 0x74, 0xb9, 0x8d, 0x38, 0x7e, 0x07, 0xbb, 0x93,
	0x4c, 0x5e, 0x96, 0x53, 0xa1, 0xe8, 0x33, 0x18, 0x7c, 0xc7, 0x6b, 0x46, 0xfc, 0x7e, 0xeb, 0x33,
	0x02, 0x7d, 0x0a, 0xce, 0x95, 0xc8, 0x7e, 0x20, 0xeb, 0xfb, 0x83, 0xc0, 0xe5, 0xf5, 0xcf, 0xf8,
	0x0c, 0x76, 0x66, 0xa8, 0xb7, 0x2e, 0x1e, 0xde, 0x2d, 0xf6, 0x83, 0x51, 0xf8, 0xe8, 0xa8, 0xa9,
	0x71, 0x86, 0xfa, 0x04, 0x13, 0x0b, 0x8a, 0x60, 0xf7, 0x3c, 0x13, 0xf9, 0x56, 0xd2, 0xab, 0x4d,
	0xd2, 0x63, 0x4b, 0x32, 0x8b, 0x1d, 0xd4, 0x07, 0x70, 0xe7, 0xba, 0x48, 0xf3, 0xaf, 0xdb, 0x58,
	0x07, 0x5d, 0x96, 0x9d, 0x34, 0x80, 0x7f, 0x04, 0x60, 0x8a, 0x5a, 0xd4, 0x27, 0xa4, 0xaf, 0xc1,
	0xb9, 0x34, 0xed, 0x30, 0xe2, 0x0f, 0x82, 0x51, 0xb8, 0x6f, 0x63, 0x6d, 0x65, 0xbc, 0x1e, 0xd3,
	0x97, 0x30, 0xcc, 0x51, 0x97, 0x55, 0x41, 0x9d, 0xd3, 0x35, 0xfd, 0xf0, 0x6a, 0x48, 0xdf, 0x80,
	0xbb, 0xb4, 0xaf, 0xa6, 0xba, 0xe4, 0x51, 0xf8, 0xc4, 0x3a, 0xdb, 0xe7, 0xc4, 0xef, 0x3c, 0x26,
	0x5d, 0x99, 0x62, 0xd8, 0x70, 0x33, 0xdd, 0xb6, 0xc5, 0xeb, 0x31, 0xfd, 0x08, 0xcf, 0x85, 0x52,
	0x59, 0x1a, 0x0b, 0x9d, 0xca, 0x7c, 0xae, 0x30, 0x4e, 0x93, 0x34, 0xae, 0x62, 0x9c, 0x6a, 0xb3,
	0x8d, 0x69, 0xcb, 0xe1, 0xf7, 0x6d, 0x4c, 0xd8, 0xcd, 0xca, 0x23, 0xb7, 0x2b, 0x8f, 0xfc, 0x5d,
	0x79, 0xe4, 0xe7, 0xda, 0xeb, 0xdd, 0xae, 0xbd, 0xde, 0xef, 0xb5, 0xd7, 0xfb, 0x1f, 0x00, 0x00,
	0xff, 0xff, 0x47, 0x25, 0x43, 0x92, 0x1c, 0x03, 0x00, 0x00,
}
