// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: predictor_consts.proto

package caffe2

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type PredictorConsts struct {
	// Important - to ensure ordered traversal of the DB, these must be
	// set in the given (lexicographic) order in the input DBReader.
	META_NET_DEF       *string `protobuf:"bytes,1,opt,name=META_NET_DEF,json=METANETDEF,def=!!META_NET_DEF" json:"META_NET_DEF,omitempty"`
	PREDICTOR_DBREADER *string `protobuf:"bytes,2,opt,name=PREDICTOR_DBREADER,json=PREDICTORDBREADER,def=!!PREDICTOR_DBREADER" json:"PREDICTOR_DBREADER,omitempty"`
	// Blob types used in MetaNetDef blobs
	PARAMETERS_BLOB_TYPE *string `protobuf:"bytes,3,opt,name=PARAMETERS_BLOB_TYPE,json=PARAMETERSBLOBTYPE,def=PARAMETERS_BLOB_TYPE" json:"PARAMETERS_BLOB_TYPE,omitempty"`
	INPUTS_BLOB_TYPE     *string `protobuf:"bytes,4,opt,name=INPUTS_BLOB_TYPE,json=INPUTSBLOBTYPE,def=INPUTS_BLOB_TYPE" json:"INPUTS_BLOB_TYPE,omitempty"`
	OUTPUTS_BLOB_TYPE    *string `protobuf:"bytes,5,opt,name=OUTPUTS_BLOB_TYPE,json=OUTPUTSBLOBTYPE,def=OUTPUTS_BLOB_TYPE" json:"OUTPUTS_BLOB_TYPE,omitempty"`
	// Net types used in MetaNetDef nets
	GLOBAL_INIT_NET_TYPE  *string `protobuf:"bytes,6,opt,name=GLOBAL_INIT_NET_TYPE,json=GLOBALINITNETTYPE,def=GLOBAL_INIT_NET_TYPE" json:"GLOBAL_INIT_NET_TYPE,omitempty"`
	PREDICT_INIT_NET_TYPE *string `protobuf:"bytes,7,opt,name=PREDICT_INIT_NET_TYPE,json=PREDICTINITNETTYPE,def=PREDICT_INIT_NET_TYPE" json:"PREDICT_INIT_NET_TYPE,omitempty"`
	PREDICT_NET_TYPE      *string `protobuf:"bytes,8,opt,name=PREDICT_NET_TYPE,json=PREDICTNETTYPE,def=PREDICT_NET_TYPE" json:"PREDICT_NET_TYPE,omitempty"`
	SINGLE_PREDICTOR      *string `protobuf:"bytes,9,opt,name=SINGLE_PREDICTOR,json=SINGLEPREDICTOR,def=SINGLE_PREDICTOR" json:"SINGLE_PREDICTOR,omitempty"`
	MULTI_PREDICTOR       *string `protobuf:"bytes,10,opt,name=MULTI_PREDICTOR,json=MULTIPREDICTOR,def=MULTI_PREDICTOR" json:"MULTI_PREDICTOR,omitempty"`
	TRAIN_INIT_PLAN_TYPE  *string `protobuf:"bytes,11,opt,name=TRAIN_INIT_PLAN_TYPE,json=TRAININITPLANTYPE,def=TRAIN_INIT_PLAN_TYPE" json:"TRAIN_INIT_PLAN_TYPE,omitempty"`
	TRAIN_PLAN_TYPE       *string `protobuf:"bytes,12,opt,name=TRAIN_PLAN_TYPE,json=TRAINPLANTYPE,def=TRAIN_PLAN_TYPE" json:"TRAIN_PLAN_TYPE,omitempty"`
}

func (m *PredictorConsts) Reset()         { *m = PredictorConsts{} }
func (m *PredictorConsts) String() string { return proto.CompactTextString(m) }
func (*PredictorConsts) ProtoMessage()    {}
func (*PredictorConsts) Descriptor() ([]byte, []int) {
	return fileDescriptor_predictor_consts_1c46709bf6102256, []int{0}
}
func (m *PredictorConsts) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PredictorConsts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PredictorConsts.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *PredictorConsts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictorConsts.Merge(dst, src)
}
func (m *PredictorConsts) XXX_Size() int {
	return m.Size()
}
func (m *PredictorConsts) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictorConsts.DiscardUnknown(m)
}

var xxx_messageInfo_PredictorConsts proto.InternalMessageInfo

const Default_PredictorConsts_META_NET_DEF string = "!!META_NET_DEF"
const Default_PredictorConsts_PREDICTOR_DBREADER string = "!!PREDICTOR_DBREADER"
const Default_PredictorConsts_PARAMETERS_BLOB_TYPE string = "PARAMETERS_BLOB_TYPE"
const Default_PredictorConsts_INPUTS_BLOB_TYPE string = "INPUTS_BLOB_TYPE"
const Default_PredictorConsts_OUTPUTS_BLOB_TYPE string = "OUTPUTS_BLOB_TYPE"
const Default_PredictorConsts_GLOBAL_INIT_NET_TYPE string = "GLOBAL_INIT_NET_TYPE"
const Default_PredictorConsts_PREDICT_INIT_NET_TYPE string = "PREDICT_INIT_NET_TYPE"
const Default_PredictorConsts_PREDICT_NET_TYPE string = "PREDICT_NET_TYPE"
const Default_PredictorConsts_SINGLE_PREDICTOR string = "SINGLE_PREDICTOR"
const Default_PredictorConsts_MULTI_PREDICTOR string = "MULTI_PREDICTOR"
const Default_PredictorConsts_TRAIN_INIT_PLAN_TYPE string = "TRAIN_INIT_PLAN_TYPE"
const Default_PredictorConsts_TRAIN_PLAN_TYPE string = "TRAIN_PLAN_TYPE"

func (m *PredictorConsts) GetMETA_NET_DEF() string {
	if m != nil && m.META_NET_DEF != nil {
		return *m.META_NET_DEF
	}
	return Default_PredictorConsts_META_NET_DEF
}

func (m *PredictorConsts) GetPREDICTOR_DBREADER() string {
	if m != nil && m.PREDICTOR_DBREADER != nil {
		return *m.PREDICTOR_DBREADER
	}
	return Default_PredictorConsts_PREDICTOR_DBREADER
}

func (m *PredictorConsts) GetPARAMETERS_BLOB_TYPE() string {
	if m != nil && m.PARAMETERS_BLOB_TYPE != nil {
		return *m.PARAMETERS_BLOB_TYPE
	}
	return Default_PredictorConsts_PARAMETERS_BLOB_TYPE
}

func (m *PredictorConsts) GetINPUTS_BLOB_TYPE() string {
	if m != nil && m.INPUTS_BLOB_TYPE != nil {
		return *m.INPUTS_BLOB_TYPE
	}
	return Default_PredictorConsts_INPUTS_BLOB_TYPE
}

func (m *PredictorConsts) GetOUTPUTS_BLOB_TYPE() string {
	if m != nil && m.OUTPUTS_BLOB_TYPE != nil {
		return *m.OUTPUTS_BLOB_TYPE
	}
	return Default_PredictorConsts_OUTPUTS_BLOB_TYPE
}

func (m *PredictorConsts) GetGLOBAL_INIT_NET_TYPE() string {
	if m != nil && m.GLOBAL_INIT_NET_TYPE != nil {
		return *m.GLOBAL_INIT_NET_TYPE
	}
	return Default_PredictorConsts_GLOBAL_INIT_NET_TYPE
}

func (m *PredictorConsts) GetPREDICT_INIT_NET_TYPE() string {
	if m != nil && m.PREDICT_INIT_NET_TYPE != nil {
		return *m.PREDICT_INIT_NET_TYPE
	}
	return Default_PredictorConsts_PREDICT_INIT_NET_TYPE
}

func (m *PredictorConsts) GetPREDICT_NET_TYPE() string {
	if m != nil && m.PREDICT_NET_TYPE != nil {
		return *m.PREDICT_NET_TYPE
	}
	return Default_PredictorConsts_PREDICT_NET_TYPE
}

func (m *PredictorConsts) GetSINGLE_PREDICTOR() string {
	if m != nil && m.SINGLE_PREDICTOR != nil {
		return *m.SINGLE_PREDICTOR
	}
	return Default_PredictorConsts_SINGLE_PREDICTOR
}

func (m *PredictorConsts) GetMULTI_PREDICTOR() string {
	if m != nil && m.MULTI_PREDICTOR != nil {
		return *m.MULTI_PREDICTOR
	}
	return Default_PredictorConsts_MULTI_PREDICTOR
}

func (m *PredictorConsts) GetTRAIN_INIT_PLAN_TYPE() string {
	if m != nil && m.TRAIN_INIT_PLAN_TYPE != nil {
		return *m.TRAIN_INIT_PLAN_TYPE
	}
	return Default_PredictorConsts_TRAIN_INIT_PLAN_TYPE
}

func (m *PredictorConsts) GetTRAIN_PLAN_TYPE() string {
	if m != nil && m.TRAIN_PLAN_TYPE != nil {
		return *m.TRAIN_PLAN_TYPE
	}
	return Default_PredictorConsts_TRAIN_PLAN_TYPE
}

func init() {
	proto.RegisterType((*PredictorConsts)(nil), "caffe2.PredictorConsts")
}
func (m *PredictorConsts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PredictorConsts) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.META_NET_DEF != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPredictorConsts(dAtA, i, uint64(len(*m.META_NET_DEF)))
		i += copy(dAtA[i:], *m.META_NET_DEF)
	}
	if m.PREDICTOR_DBREADER != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPredictorConsts(dAtA, i, uint64(len(*m.PREDICTOR_DBREADER)))
		i += copy(dAtA[i:], *m.PREDICTOR_DBREADER)
	}
	if m.PARAMETERS_BLOB_TYPE != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintPredictorConsts(dAtA, i, uint64(len(*m.PARAMETERS_BLOB_TYPE)))
		i += copy(dAtA[i:], *m.PARAMETERS_BLOB_TYPE)
	}
	if m.INPUTS_BLOB_TYPE != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintPredictorConsts(dAtA, i, uint64(len(*m.INPUTS_BLOB_TYPE)))
		i += copy(dAtA[i:], *m.INPUTS_BLOB_TYPE)
	}
	if m.OUTPUTS_BLOB_TYPE != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintPredictorConsts(dAtA, i, uint64(len(*m.OUTPUTS_BLOB_TYPE)))
		i += copy(dAtA[i:], *m.OUTPUTS_BLOB_TYPE)
	}
	if m.GLOBAL_INIT_NET_TYPE != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintPredictorConsts(dAtA, i, uint64(len(*m.GLOBAL_INIT_NET_TYPE)))
		i += copy(dAtA[i:], *m.GLOBAL_INIT_NET_TYPE)
	}
	if m.PREDICT_INIT_NET_TYPE != nil {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintPredictorConsts(dAtA, i, uint64(len(*m.PREDICT_INIT_NET_TYPE)))
		i += copy(dAtA[i:], *m.PREDICT_INIT_NET_TYPE)
	}
	if m.PREDICT_NET_TYPE != nil {
		dAtA[i] = 0x42
		i++
		i = encodeVarintPredictorConsts(dAtA, i, uint64(len(*m.PREDICT_NET_TYPE)))
		i += copy(dAtA[i:], *m.PREDICT_NET_TYPE)
	}
	if m.SINGLE_PREDICTOR != nil {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintPredictorConsts(dAtA, i, uint64(len(*m.SINGLE_PREDICTOR)))
		i += copy(dAtA[i:], *m.SINGLE_PREDICTOR)
	}
	if m.MULTI_PREDICTOR != nil {
		dAtA[i] = 0x52
		i++
		i = encodeVarintPredictorConsts(dAtA, i, uint64(len(*m.MULTI_PREDICTOR)))
		i += copy(dAtA[i:], *m.MULTI_PREDICTOR)
	}
	if m.TRAIN_INIT_PLAN_TYPE != nil {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintPredictorConsts(dAtA, i, uint64(len(*m.TRAIN_INIT_PLAN_TYPE)))
		i += copy(dAtA[i:], *m.TRAIN_INIT_PLAN_TYPE)
	}
	if m.TRAIN_PLAN_TYPE != nil {
		dAtA[i] = 0x62
		i++
		i = encodeVarintPredictorConsts(dAtA, i, uint64(len(*m.TRAIN_PLAN_TYPE)))
		i += copy(dAtA[i:], *m.TRAIN_PLAN_TYPE)
	}
	return i, nil
}

func encodeVarintPredictorConsts(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *PredictorConsts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.META_NET_DEF != nil {
		l = len(*m.META_NET_DEF)
		n += 1 + l + sovPredictorConsts(uint64(l))
	}
	if m.PREDICTOR_DBREADER != nil {
		l = len(*m.PREDICTOR_DBREADER)
		n += 1 + l + sovPredictorConsts(uint64(l))
	}
	if m.PARAMETERS_BLOB_TYPE != nil {
		l = len(*m.PARAMETERS_BLOB_TYPE)
		n += 1 + l + sovPredictorConsts(uint64(l))
	}
	if m.INPUTS_BLOB_TYPE != nil {
		l = len(*m.INPUTS_BLOB_TYPE)
		n += 1 + l + sovPredictorConsts(uint64(l))
	}
	if m.OUTPUTS_BLOB_TYPE != nil {
		l = len(*m.OUTPUTS_BLOB_TYPE)
		n += 1 + l + sovPredictorConsts(uint64(l))
	}
	if m.GLOBAL_INIT_NET_TYPE != nil {
		l = len(*m.GLOBAL_INIT_NET_TYPE)
		n += 1 + l + sovPredictorConsts(uint64(l))
	}
	if m.PREDICT_INIT_NET_TYPE != nil {
		l = len(*m.PREDICT_INIT_NET_TYPE)
		n += 1 + l + sovPredictorConsts(uint64(l))
	}
	if m.PREDICT_NET_TYPE != nil {
		l = len(*m.PREDICT_NET_TYPE)
		n += 1 + l + sovPredictorConsts(uint64(l))
	}
	if m.SINGLE_PREDICTOR != nil {
		l = len(*m.SINGLE_PREDICTOR)
		n += 1 + l + sovPredictorConsts(uint64(l))
	}
	if m.MULTI_PREDICTOR != nil {
		l = len(*m.MULTI_PREDICTOR)
		n += 1 + l + sovPredictorConsts(uint64(l))
	}
	if m.TRAIN_INIT_PLAN_TYPE != nil {
		l = len(*m.TRAIN_INIT_PLAN_TYPE)
		n += 1 + l + sovPredictorConsts(uint64(l))
	}
	if m.TRAIN_PLAN_TYPE != nil {
		l = len(*m.TRAIN_PLAN_TYPE)
		n += 1 + l + sovPredictorConsts(uint64(l))
	}
	return n
}

func sovPredictorConsts(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozPredictorConsts(x uint64) (n int) {
	return sovPredictorConsts(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PredictorConsts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPredictorConsts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PredictorConsts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PredictorConsts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field META_NET_DEF", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPredictorConsts
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.META_NET_DEF = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PREDICTOR_DBREADER", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPredictorConsts
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.PREDICTOR_DBREADER = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PARAMETERS_BLOB_TYPE", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPredictorConsts
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.PARAMETERS_BLOB_TYPE = &s
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field INPUTS_BLOB_TYPE", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPredictorConsts
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.INPUTS_BLOB_TYPE = &s
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OUTPUTS_BLOB_TYPE", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPredictorConsts
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.OUTPUTS_BLOB_TYPE = &s
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GLOBAL_INIT_NET_TYPE", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPredictorConsts
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.GLOBAL_INIT_NET_TYPE = &s
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PREDICT_INIT_NET_TYPE", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPredictorConsts
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.PREDICT_INIT_NET_TYPE = &s
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PREDICT_NET_TYPE", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPredictorConsts
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.PREDICT_NET_TYPE = &s
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SINGLE_PREDICTOR", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPredictorConsts
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.SINGLE_PREDICTOR = &s
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MULTI_PREDICTOR", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPredictorConsts
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.MULTI_PREDICTOR = &s
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TRAIN_INIT_PLAN_TYPE", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPredictorConsts
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.TRAIN_INIT_PLAN_TYPE = &s
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TRAIN_PLAN_TYPE", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPredictorConsts
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.TRAIN_PLAN_TYPE = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPredictorConsts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPredictorConsts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPredictorConsts(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPredictorConsts
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPredictorConsts
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthPredictorConsts
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPredictorConsts
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPredictorConsts(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPredictorConsts = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPredictorConsts   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("predictor_consts.proto", fileDescriptor_predictor_consts_1c46709bf6102256)
}

var fileDescriptor_predictor_consts_1c46709bf6102256 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0x86, 0xe9, 0xef, 0x0f, 0xca, 0x88, 0x2d, 0xdd, 0x54, 0xd3, 0x53, 0x63, 0x3d, 0x79, 0x32,
	0xc6, 0x8b, 0x06, 0xe3, 0xa1, 0xa5, 0x0b, 0x36, 0x29, 0xdb, 0x66, 0x58, 0x0e, 0x9e, 0x36, 0x06,
	0x21, 0xf1, 0x62, 0x09, 0xf0, 0x3d, 0xf4, 0x63, 0x79, 0xe4, 0xe8, 0xd1, 0xc0, 0x17, 0x31, 0xdd,
	0xa5, 0xa5, 0x29, 0x3d, 0xf6, 0x79, 0xe7, 0x79, 0x33, 0x9d, 0x85, 0xf3, 0xf9, 0x62, 0xfa, 0xfa,
	0x36, 0x59, 0xa5, 0x0b, 0x31, 0x49, 0xdf, 0x97, 0xab, 0xe5, 0xf5, 0x7c, 0x91, 0xae, 0x52, 0xd2,
	0x9c, 0xbc, 0xcc, 0x66, 0xd3, 0xdb, 0xcb, 0x8f, 0x26, 0x18, 0x49, 0x3e, 0xd2, 0x93, 0x13, 0xe4,
	0x06, 0xda, 0x43, 0xca, 0x3d, 0xc1, 0x28, 0x17, 0x01, 0xed, 0xdb, 0xda, 0x85, 0x76, 0xd5, 0xea,
	0xea, 0xae, 0x5b, 0xa6, 0x08, 0xd9, 0x17, 0xa3, 0x3c, 0xa0, 0x7d, 0xd2, 0x03, 0x92, 0x20, 0x0d,
	0xc2, 0x1e, 0x8f, 0x51, 0x04, 0x3e, 0x52, 0x2f, 0xa0, 0x68, 0xff, 0x91, 0x9e, 0xe5, 0xba, 0x87,
	0x19, 0x9a, 0x05, 0xcb, 0x11, 0xe9, 0x83, 0x95, 0x78, 0xe8, 0x0d, 0x29, 0xa7, 0x38, 0x12, 0x7e,
	0x14, 0xfb, 0x82, 0x3f, 0x27, 0xd4, 0xfe, 0xab, 0x6a, 0xea, 0x32, 0x24, 0x7b, 0x9a, 0xc1, 0x8c,
	0x91, 0x2e, 0x74, 0x42, 0x96, 0x8c, 0x79, 0xb9, 0xe3, 0x9f, 0xec, 0x38, 0xe0, 0xa8, 0x2b, 0x52,
	0xb8, 0x8f, 0x60, 0xc6, 0x63, 0x5e, 0x91, 0xff, 0x4b, 0xf9, 0x30, 0x40, 0x63, 0x87, 0x0a, 0x9d,
	0x82, 0x35, 0x88, 0x62, 0xdf, 0x8b, 0x44, 0xc8, 0x42, 0x2e, 0x4f, 0x25, 0x1b, 0x9a, 0xea, 0x17,
	0xea, 0x32, 0x34, 0x15, 0xcd, 0x20, 0xa3, 0x5c, 0xd6, 0x3c, 0xc1, 0xd9, 0xee, 0x3c, 0x95, 0x9e,
	0x23, 0xd9, 0x53, 0x1f, 0x62, 0xfe, 0x04, 0xe5, 0xa6, 0x2e, 0x74, 0xf2, 0xe1, 0xa2, 0xe4, 0x58,
	0xdd, 0xa2, 0xca, 0x51, 0xdf, 0x91, 0xdc, 0x7d, 0x80, 0xce, 0x28, 0x64, 0x83, 0x88, 0x8a, 0xe2,
	0xad, 0xec, 0x96, 0x72, 0xab, 0x1c, 0x0d, 0x45, 0x0a, 0x40, 0xee, 0xc1, 0x18, 0x8e, 0x23, 0x1e,
	0x96, 0x5c, 0x90, 0x6e, 0x15, 0xa3, 0x2e, 0xc1, 0xde, 0xa4, 0x60, 0x71, 0xf4, 0x42, 0xa6, 0xfe,
	0x2e, 0x89, 0x3c, 0xa6, 0xd6, 0x3e, 0x51, 0x37, 0xac, 0xcb, 0xd0, 0x94, 0x34, 0x83, 0x19, 0x93,
	0xdb, 0xdf, 0x81, 0xa1, 0x46, 0xf7, 0x0d, 0x6d, 0xb5, 0x40, 0x05, 0xe3, 0xa9, 0x04, 0xb9, 0xe8,
	0xdb, 0x5f, 0x1b, 0x47, 0x5b, 0x6f, 0x1c, 0xed, 0x67, 0xe3, 0x68, 0x9f, 0x5b, 0xa7, 0xb1, 0xde,
	0x3a, 0x8d, 0xef, 0xad, 0xd3, 0xf8, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x38, 0x9e, 0x69, 0x4c,
	0x03, 0x00, 0x00,
}
